name: ESS App CI/CD

on:
  push:
    branches:
      - main   

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (root)
        run: npm install

      - name: Install & build frontend
        if: -f ./frontend/package.json
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Install & test backend
        if: -f ./backend/package.json
        working-directory: ./backend
        run: |
          npm install
          npm test

      - name: Lint code
        run: |
          npm run lint || echo "No lint script detected"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || '22' }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/ess || exit 1
            git pull origin main
            npm install --production
            pm2 restart ess || pm2 start ./backend/index.js --name ess
